# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
relative_permalinks: false
plugins: - jekyll-gist
  - jekyll-paginate

safe: true

whitelist:
  - jekyll-gist
  - jekyll-paginate

# Setup
title:            Barista Betrayal
tagline:          'Board game project for IAT 210'
description:      'Board game based on  whatever whatever'
url:              https://gsa153.github.io/
baseurl:          ""

author:
  name:           ''
  url:            https://gsa153.github.io/

paginate:         5

# Custom vars
#version:          4.4.1

github:
  repo:           https://github.com/gsa153/gsa153.github.io/
