# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

plugins:
  - jekyll-gist
  - jekyll-paginate

safe: true

whitelist:
  - jekyll-gist
  - jekyll-paginate

# Setup
title:            Barista Betrayal
tagline:          'Board game project for IAT 210'
description:      'Board game based on  whatever whatever'
url:              https://gursewaktut.github.io/baristabetrayalproject/
baseurl:          https://gursewaktut.github.io/baristabetrayalproject/

author:
  name:           ''
  url:            https://gursewaktut.github.io/baristabetrayalproject/

paginate:         5

# Custom vars
#version:          4.4.1

github:
  repo:           https://github.com/gursewaktut/baristabetrayalproject
